-- MySQL Script generated by MySQL Workbench
-- Fri Mar  3 12:27:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema myCine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myCine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myCine` DEFAULT CHARACTER SET latin1 ;
USE `myCine` ;

-- -----------------------------------------------------
-- Table `myCine`.`Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`Actor` (
  `idActor` INT(11) NOT NULL AUTO_INCREMENT,
  `fName` VARCHAR(45) NOT NULL,
  `lName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idActor`),
  UNIQUE INDEX `idActor_UNIQUE` (`idActor` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myCine`.`States`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`States` (
  `idState` INT(11) NOT NULL AUTO_INCREMENT,
  `Short_name` VARCHAR(45) NOT NULL,
  `Long_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idState`))
ENGINE = InnoDB
AUTO_INCREMENT = 56
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myCine`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`Addresses` (
  `idAddresses` INT(11) NOT NULL AUTO_INCREMENT,
  `StreetAddress1` VARCHAR(45) NOT NULL,
  `StreetAddress2` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NOT NULL,
  `State` INT(11) NOT NULL,
  `ZipCode` INT(11) NOT NULL,
  PRIMARY KEY (`idAddresses`),
  UNIQUE INDEX `idAddresses_UNIQUE` (`idAddresses` ASC),
  INDEX `stateID_idx` (`State` ASC),
  CONSTRAINT `stateID`
    FOREIGN KEY (`State`)
    REFERENCES `myCine`.`States` (`idState`))
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myCine`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`Director` (
  `idDirector` INT(11) NOT NULL,
  `fName` VARCHAR(45) NOT NULL,
  `lName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDirector`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myCine`.`Format`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`Format` (
  `idFormat` INT(11) NOT NULL AUTO_INCREMENT,
  `formatTitle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFormat`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myCine`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`Genre` (
  `idGenre` INT(11) NOT NULL,
  `genreTitle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myCine`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fName` VARCHAR(45) NOT NULL,
  `lName` VARCHAR(45) NOT NULL,
  `reminderThreshold` INT(11) NOT NULL,
  `defaultRentalPeriod` INT(11) NOT NULL,
  `address` INT(11) NOT NULL,
  `cell_number` VARCHAR(45) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `user_name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cellNumber_UNIQUE` (`cell_number` ASC),
  UNIQUE INDEX `email_UNIQUE` (`user_name` ASC),
  UNIQUE INDEX `UUID_UNIQUE` (`id` ASC),
  INDEX `addressID_idx` (`address` ASC),
  CONSTRAINT `addressID`
    FOREIGN KEY (`address`)
    REFERENCES `myCine`.`Addresses` (`idAddresses`))
ENGINE = InnoDB
AUTO_INCREMENT = 76
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myCine`.`MessageLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`MessageLog` (
  `idMessageLog` INT(11) NOT NULL,
  `senderID` INT(11) NOT NULL,
  `recipientID` INT(11) NOT NULL,
  `messageBody` LONGTEXT NOT NULL,
  `dateTime` DATETIME NOT NULL,
  PRIMARY KEY (`idMessageLog`),
  INDEX `recipientID_idx` (`recipientID` ASC),
  INDEX `senderID_idx` (`senderID` ASC),
  CONSTRAINT `recipientID`
    FOREIGN KEY (`recipientID`)
    REFERENCES `myCine`.`users` (`id`),
  CONSTRAINT `senderID`
    FOREIGN KEY (`senderID`)
    REFERENCES `myCine`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myCine`.`Studio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`Studio` (
  `idStudio` INT(11) NOT NULL,
  `studioTitle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStudio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myCine`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`Movie` (
  `idMovie` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `format` INT(11) NOT NULL,
  `genre` INT(11) NOT NULL,
  `director` INT(11) NOT NULL,
  `studio` INT(11) NOT NULL,
  `imdbID` VARCHAR(45) NULL DEFAULT NULL,
  `upcCode` BIGINT(20) NULL DEFAULT NULL,
  `releaseDate` DATE NOT NULL,
  `imgSource` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`idMovie`),
  INDEX `directorID_idx` (`director` ASC),
  INDEX `formatID_idx` (`format` ASC),
  INDEX `genreID_idx` (`genre` ASC),
  INDEX `studioID_idx` (`studio` ASC),
  CONSTRAINT `directorID`
    FOREIGN KEY (`director`)
    REFERENCES `myCine`.`Director` (`idDirector`),
  CONSTRAINT `formatID`
    FOREIGN KEY (`format`)
    REFERENCES `myCine`.`Format` (`idFormat`),
  CONSTRAINT `genreID`
    FOREIGN KEY (`genre`)
    REFERENCES `myCine`.`Genre` (`idGenre`),
  CONSTRAINT `studioID`
    FOREIGN KEY (`studio`)
    REFERENCES `myCine`.`Studio` (`idStudio`))
ENGINE = InnoDB
AUTO_INCREMENT = 95
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myCine`.`MovieCast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`MovieCast` (
  `idMovieCast` INT(11) NOT NULL,
  `filmID` INT(11) NOT NULL,
  `actorID` INT(11) NOT NULL,
  PRIMARY KEY (`idMovieCast`),
  INDEX `actorID_idx` (`actorID` ASC),
  INDEX `filmID_idx` (`filmID` ASC),
  CONSTRAINT `actorID`
    FOREIGN KEY (`actorID`)
    REFERENCES `myCine`.`Actor` (`idActor`),
  CONSTRAINT `filmID`
    FOREIGN KEY (`filmID`)
    REFERENCES `myCine`.`Movie` (`idMovie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myCine`.`UserMovie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`UserMovie` (
  `linkID` INT(11) NOT NULL,
  `userID` INT(11) NOT NULL,
  `movieID` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `starRating` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`linkID`),
  UNIQUE INDEX `linkID_UNIQUE` (`linkID` ASC),
  INDEX `movieID_idx` (`movieID` ASC),
  INDEX `ownerID_idx` (`userID` ASC),
  CONSTRAINT `movieUUID`
    FOREIGN KEY (`movieID`)
    REFERENCES `myCine`.`Movie` (`idMovie`),
  CONSTRAINT `ownerID`
    FOREIGN KEY (`userID`)
    REFERENCES `myCine`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myCine`.`Rentals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`Rentals` (
  `idRentals` INT(11) NOT NULL,
  `renterID` INT(11) NOT NULL,
  `movieID` INT(11) NOT NULL,
  `dueDate` DATETIME NOT NULL,
  PRIMARY KEY (`idRentals`),
  INDEX `rentalMovieID_idx` (`movieID` ASC),
  INDEX `renterID_idx` (`renterID` ASC),
  CONSTRAINT `rentalMovieID`
    FOREIGN KEY (`movieID`)
    REFERENCES `myCine`.`UserMovie` (`linkID`),
  CONSTRAINT `renterID`
    FOREIGN KEY (`renterID`)
    REFERENCES `myCine`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myCine`.`UserFriends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`UserFriends` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `friend_a` INT(11) NOT NULL,
  `friend_b` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `friend_a_idx` (`friend_a` ASC),
  INDEX `friend_b_idx` (`friend_b` ASC),
  CONSTRAINT `friend_a`
    FOREIGN KEY (`friend_a`)
    REFERENCES `myCine`.`users` (`id`),
  CONSTRAINT `friend_b`
    FOREIGN KEY (`friend_b`)
    REFERENCES `myCine`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myCine`.`UserRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`UserRoles` (
  `user_name` VARCHAR(128) NOT NULL,
  `role_name` VARCHAR(128) NOT NULL,
  `roleID` INT(11) NOT NULL,
  PRIMARY KEY (`roleID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myCine`.`WishList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myCine`.`WishList` (
  `idWishListLink` INT(11) NOT NULL,
  `userID` INT(11) NOT NULL,
  `movieID` INT(11) NOT NULL,
  PRIMARY KEY (`idWishListLink`),
  UNIQUE INDEX `idWishListLink_UNIQUE` (`idWishListLink` ASC),
  INDEX `movieID_idx` (`movieID` ASC),
  CONSTRAINT `movieID`
    FOREIGN KEY (`movieID`)
    REFERENCES `myCine`.`Movie` (`idMovie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('1', 'AL', 'Alabama');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('2', 'AK', 'Alaska');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('3', 'AZ', 'Arizona');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('4', 'AR', 'Arkansas');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('5', 'CA', 'California');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('6', 'CO', 'Colorado');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('7', 'CT', 'Connecticut');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('8', 'DE', 'Delaware');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('9', 'FL', 'Florida');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('10', 'GA', 'Georgia');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('11', 'HI', 'Hawaii');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('12', 'ID', 'Idaho');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('13', 'IL', 'Illinois');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('14', 'IN', 'Indiana');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('15', 'IA', 'Iowa');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('16', 'KS', 'Kansas');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('17', 'KY', 'Kentucky');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('18', 'LA', 'Louisiana');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('19', 'ME', 'Maine');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('20', 'MD', 'Maryland');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('21', 'MA', 'Massachusetts');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('22', 'MI', 'Michigan');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('23', 'MN', 'Minnesota');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('24', 'MS', 'Mississippi');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('25', 'MO', 'Missouri');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('26', 'MT', 'Montana');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('27', 'NE', 'Nebraska');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('28', 'NV', 'Nevada');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('29', 'NH', 'New Hampshire');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('30', 'NJ', 'New Jersey');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('31', 'NM', 'New Mexico');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('32', 'NY', 'New York');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('33', 'NC', 'North Carolina');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('34', 'ND', 'North Dakota');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('35', 'OH', 'Ohio');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('36', 'OK', 'Oklahoma');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('37', 'OR', 'Oregon');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('38', 'PA', 'Pennsylvania');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('39', 'RI', 'Rhode Island');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('40', 'SC', 'South Carolina');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('41', 'SD', 'South Dakota');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('42', 'TN', 'Tennessee');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('43', 'TX', 'Texas');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('44', 'UT', 'Utah');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('45', 'VT', 'Vermont');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('46', 'VA', 'Virginia');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('47', 'WA', 'Washington');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('48', 'WV', 'West Virginia');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('49', 'WI', 'Wisconsin');
INSERT INTO `myCine`.`States` (`idState`, `Short_name`, `Long_name`) VALUES ('50', 'WY', 'Wyoming');

insert into Addresses values (1, "605 Park St", "", "Madison", 49, 53098);
insert into users (id, user_name, fName, lName, address, cell_number, reminderThreshold, defaultRentalPeriod, password) values (1, "admin", "admin", "admin" , 1, 1234567890, 1, 1, "E651DF1EA9152CFF31324AA4DC2ADAC1E62A001BD75C2EFBAFC09AE207E7F8D0");
insert into UserRoles (roleID, user_name, role_name) values (1, "admin", "administrator");
insert into Actor (idActor, fName, lName)  values (1, "unknown", "unknown");
insert into Director (idDirector, fName, lName) values (1, "unknown", "unknown");
insert into Format (idFormat, formatTitle) values (1, "DVD");
insert into Genre (idGenre, genreTitle) values (1, "unknown");
insert into Studio (idStudio, studioTitle) values (1, "unknown");
